[tool.poetry]
name = "tidypolars"
version = "0.1.0"
description = "Tidy interface to polars"
authors = ["Mark Fairbanks"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
polars = ">=0.9.12"
numpy = ">=1.21.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
